name: eyerizer
description: An app that help people with colorblindness see colors accurately.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  permission_handler: ^10.2.0
  camera: ^0.10.0+4
  flutter_bloc: ^8.1.1
  equatable: ^2.0.5
  logger: ^1.1.0
  palette_generator: ^0.3.3+2
  sizer: ^2.0.15
  image: ^3.2.2
  flutter_svg: ^1.1.6
  image_picker: ^0.8.6
  auto_animated: ^3.1.0
  flutter_staggered_grid_view: ^0.6.2
  measure_size: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/palates/
#     fonts:
#       - family: Google Sans
#         fonts:
#           - asset: assets/fonts/Schyler-Regular.ttf
#           - asset: fonts/Schyler-Italic.ttf
#             style: italic