import 'package:flutter/material.dart';

final Map<Color, String> colorNames = {
  const Color(0xFFCD5C5C): 'Indian Red',
  const Color(0xFFF08080): 'Light Coral',
  const Color(0xFFFA8072): 'Salmon',
  const Color(0xFFE9967A): 'Dark Salmon',
  const Color(0xFFFFA07A): 'Light Salmon',
  const Color(0xFFDC143C): 'Crimson',
  const Color(0xFFFF0000): 'Red',
  const Color(0xFFB22222): 'Fire Brick',
  const Color(0xFF8B0000): 'Dark Red',
  const Color(0xFFFFC0CB): 'Pink',
  const Color(0xFFFFB6C1): 'Light Pink',
  const Color(0xFFFF69B4): 'Hot Pink',
  const Color(0xFFFF1493): 'Deep Pink',
  const Color(0xFFC71585): 'Medium Violet Red',
  const Color(0xFFDB7093): 'Pale Violet Red',
  const Color(0xFFFFA07A): 'Light Salmon',
  const Color(0xFFFF7F50): 'Coral',
  const Color(0xFFFF6347): 'Tomato',
  const Color(0xFFFF4500): 'Orange Red',
  const Color(0xFFFF8C00): 'Dark Orange',
  const Color(0xFFFFA500): 'Orange',
  const Color(0xFFFFD700): 'Gold',
  const Color(0xFFFFFF00): 'Yellow',
  const Color(0xFFFFFFE0): 'Light Yellow',
  const Color(0xFFFFFACD): 'Lemon Chiffon',
  const Color(0xFFFAFAD2): 'Light Goldenrod Yellow',
  const Color(0xFFFFEFD5): 'Papaya Whip',
  const Color(0xFFFFE4B5): 'Moccasin',
  const Color(0xFFFFDAB9): 'Peach Puff',
  const Color(0xFFEEE8AA): 'Pale Goldenrod',
  const Color(0xFFF0E68C): 'Khaki',
  const Color(0xFFBDB76B): 'Dark Khaki',
  const Color(0xFFE6E6FA): 'Lavender',
  const Color(0xFFD8BFD8): 'Thistle',
  const Color(0xFFDDA0DD): 'Plum',
  const Color(0xFFEE82EE): 'Violet',
  const Color(0xFFDA70D6): 'Orchid',
  const Color(0xFFFF00FF): 'Fuchsia',
  const Color(0xFFFF00FF): 'Magenta',
  const Color(0xFFBA55D3): 'Medium Orchid',
  const Color(0xFF9370DB): 'Medium Purple',
  const Color(0xFF663399): 'Rebecca Purple',
  const Color(0xFF8A2BE2): 'Blue Violet',
  const Color(0xFF9400D3): 'Dark Violet',
  const Color(0xFF9932CC): 'Dark Orchid',
  const Color(0xFF8B008B): 'Dark Magenta',
  const Color(0xFF800080): 'Purple',
  const Color(0xFF4B0082): 'Indigo',
  const Color(0xFF6A5ACD): 'Slate Blue',
  const Color(0xFF483D8B): 'Dark Slate Blue',
  const Color(0xFF7B68EE): 'Medium Slate Blue',
  const Color(0xFFADFF2F): 'Green Yellow',
  const Color(0xFF7FFF00): 'Chartreuse',
  const Color(0xFF7CFC00): 'Lawn Green',
  const Color(0xFF00FF00): 'Lime',
  const Color(0xFF32CD32): 'Lime Green',
  const Color(0xFF98FB98): 'Pale Green',
  const Color(0xFF90EE90): 'Light Green',
  const Color(0xFF00FA9A): 'Medium Spring Green',
  const Color(0xFF00FF7F): 'Spring Green',
  const Color(0xFF3CB371): 'Medium Sea Green',
  const Color(0xFF2E8B57): 'Sea Green',
  const Color(0xFF228B22): 'Forest Green',
  const Color(0xFF008000): 'Green',
  const Color(0xFF006400): 'Dark Green',
  const Color(0xFF9ACD32): 'Yellow Green',
  const Color(0xFF6B8E23): 'Olive Drab',
  const Color(0xFF808000): 'Olive',
  const Color(0xFF556B2F): 'Dark Olive Green',
  const Color(0xFF66CDAA): 'Medium Aquamarine',
  const Color(0xFF8FBC8B): 'Dark Sea Green',
  const Color(0xFF20B2AA): 'Light Sea Green',
  const Color(0xFF008B8B): 'Dark Cyan',
  const Color(0xFF008080): 'Teal',
  const Color(0xFF00FFFF): 'Aqua',
  const Color(0xFF00FFFF): 'Cyan',
  const Color(0xFFE0FFFF): 'Light Cyan',
  const Color(0xFFAFEEEE): 'Pale Turquoise',
  const Color(0xFF7FFFD4): 'Aquamarine',
  const Color(0xFF40E0D0): 'Turquoise',
  const Color(0xFF48D1CC): 'Medium Turquoise',
  const Color(0xFF00CED1): 'Dark Turquoise',
  const Color(0xFF5F9EA0): 'Cadet Blue',
  const Color(0xFF4682B4): 'Steel Blue',
  const Color(0xFFB0C4DE): 'Light Steel Blue',
  const Color(0xFFB0E0E6): 'Powder Blue',
  const Color(0xFFADD8E6): 'Light Blue',
  const Color(0xFF87CEEB): 'Sky Blue',
  const Color(0xFF87CEFA): 'Light Sky Blue',
  const Color(0xFF00BFFF): 'Deep Sky Blue',
  const Color(0xFF1E90FF): 'Dodger Blue',
  const Color(0xFF6495ED): 'Cornflower Blue',
  const Color(0xFF7B68EE): 'Medium Slate Blue',
  const Color(0xFF4169E1): 'Royal Blue',
  const Color(0xFF0000FF): 'Blue',
  const Color(0xFF0000CD): 'Medium Blue',
  const Color(0xFF00008B): 'Dark Blue',
  const Color(0xFF000080): 'Navy',
  const Color(0xFF191970): 'Midnight Blue',
  const Color(0xFFFFF8DC): 'Cornsilk',
  const Color(0xFFFFEBCD): 'Blanched Almond',
  const Color(0xFFFFE4C4): 'Bisque',
  const Color(0xFFFFDEAD): 'Navajo White',
  const Color(0xFFF5DEB3): 'Wheat',
  const Color(0xFFDEB887): 'Burly Wood',
  const Color(0xFFD2B48C): 'Tan',
  const Color(0xFFBC8F8F): 'Rosy Brown',
  const Color(0xFFF4A460): 'Sandy Brown',
  const Color(0xFFDAA520): 'Goldenrod',
  const Color(0xFFB8860B): 'Dark Goldenrod',
  const Color(0xFFCD853F): 'Peru',
  const Color(0xFFD2691E): 'Chocolate',
  const Color(0xFF8B4513): 'Saddle Brown',
  const Color(0xFFA0522D): 'Sienna',
  const Color(0xFFA52A2A): 'Brown',
  const Color(0xFF800000): 'Maroon',
  const Color(0xFFFFFFFF): 'White',
  const Color(0xFFFFFAFA): 'Snow',
  const Color(0xFFF0FFF0): 'Honey Dew',
  const Color(0xFFF5FFFA): 'Mint Cream',
  const Color(0xFFF0FFFF): 'Azure',
  const Color(0xFFF0F8FF): 'Alice Blue',
  const Color(0xFFF8F8FF): 'Ghost White',
  const Color(0xFFF5F5F5): 'White Smoke',
  const Color(0xFFFFF5EE): 'Sea Shell',
  const Color(0xFFF5F5DC): 'Beige',
  const Color(0xFFFDF5E6): 'Old Lace',
  const Color(0xFFFFFAF0): 'Floral White',
  const Color(0xFFFFFFF0): 'Ivory',
  const Color(0xFFFAEBD7): 'Antique White',
  const Color(0xFFFAF0E6): 'Linen',
  const Color(0xFFFFF0F5): 'Lavender Blush',
  const Color(0xFFFFE4E1): 'Misty Rose',
  const Color(0xFFDCDCDC): 'Gainsboro',
  const Color(0xFFD3D3D3): 'Light Gray',
  const Color(0xFFC0C0C0): 'Silver',
  const Color(0xFFA9A9A9): 'Dark Gray',
  const Color(0xFF808080): 'Gray',
  const Color(0xFF696969): 'Dim Gray',
  const Color(0xFF778899): 'Light Slate Gray',
  const Color(0xFF708090): 'Slate Gray',
  const Color(0xFF2F4F4F): 'Dark Slate Gray',
  const Color(0xFF000000): 'Black',
};
